compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@parcel/node-resolver-core@*":
    dependencies:
      "@parcel/core": 2.12.0
  "@parcel/workers@*":
    dependencies:
      "@parcel/core": 2.12.0
