# TODO: Remove this file once workaround is no longer needed.
compressionLevel: mixed
enableGlobalCache: false
packageExtensions:
  "@parcel/node-resolver-core@*":
    dependencies:
      "@parcel/core": 2.12.0
  "@parcel/workers@*":
    dependencies:
      "@parcel/core": 2.12.0
