name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Enable Corepack
      run: npm install --global --force corepack && corepack enable

    - name: Set up latest Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'yarn'
        node-version: latest

    - name: Set up Go 1.22
      uses: actions/setup-go@v4
      with:
        cache: true
        go-version: ^1.22
      id: go

    - name: Install dependencies on Ubuntu
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends libwebkit2gtk-4.0-dev
      if: ${{ success() && matrix.os == 'ubuntu-22.04' }}

    - name: Get dependencies
      run: |
        yarn install --immutable
        go get -v -t -d ./...

    - name: Build
      run: yarn build

    - name: Test
      run: yarn lint && go test -v ./...
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: imprint-${{ runner.os }}
        path: imprint*
